all:
  hosts:
        web1:
          ansible_host: 158.160.116.176
          ansible_user: ubuntu
        web2:
          ansible_host: 158.160.122.231
          ansible_user: ubuntu
        storage:
          ansible_host: 158.160.125.112
          ansible_user: ubuntu
                    main:
          ansible_host: 51.250.84.182
          ansible_user: ubuntu
            replica:
          ansible_host: 89.169.158.173
          ansible_user: ubuntu
        